package company.entity;
// Generated Dec 14, 2018 12:08:36 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DocumentManagement generated by hbm2java
 */
@Entity
@Table(name = "document_management", catalog = "companymanagement")
public class DocumentManagement implements java.io.Serializable {

	private Integer idDocument;
	private String typeOfDocument;
	private String icon;
	private Integer rights;
	private String category;
	private String file;
	private String status;
	private String note;
	private Integer idProject;

	public DocumentManagement() {
	}

	public DocumentManagement(String typeOfDocument, String icon, Integer rights, String category, String file,
			String status, String note, Integer idProject) {
		this.typeOfDocument = typeOfDocument;
		this.icon = icon;
		this.rights = rights;
		this.category = category;
		this.file = file;
		this.status = status;
		this.note = note;
		this.idProject = idProject;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_document", unique = true, nullable = false)
	public Integer getIdDocument() {
		return this.idDocument;
	}

	public void setIdDocument(Integer idDocument) {
		this.idDocument = idDocument;
	}

	@Column(name = "typeOfDocument", length = 45)
	public String getTypeOfDocument() {
		return this.typeOfDocument;
	}

	public void setTypeOfDocument(String typeOfDocument) {
		this.typeOfDocument = typeOfDocument;
	}

	@Column(name = "icon", length = 45)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "rights")
	public Integer getRights() {
		return this.rights;
	}

	public void setRights(Integer rights) {
		this.rights = rights;
	}

	@Column(name = "category", length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "file", length = 45)
	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

	@Column(name = "status", length = 65535)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "note", length = 100)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "id_project")
	public Integer getIdProject() {
		return this.idProject;
	}

	public void setIdProject(Integer idProject) {
		this.idProject = idProject;
	}

}
