package company.entity;
// Generated Dec 14, 2018 12:08:36 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeProfile generated by hbm2java
 */
@Entity
@Table(name = "employee_profile", catalog = "companymanagement")
public class EmployeeProfile implements java.io.Serializable {

	private Integer idEmployee;
	private String name;
	private Integer sex;
	private Date dayOfBirth;
	private String address;
	private String contact;
	private String email;
	private String introduction;
	private Integer idRights;
	private String note;
	private Integer idDepartment;
	private Date dayOfRest;

	public EmployeeProfile() {
	}

	public EmployeeProfile(String name, Integer sex, Date dayOfBirth, String address, String contact, String email,
			String introduction, Integer idRights, String note, Integer idDepartment, Date dayOfRest) {
		this.name = name;
		this.sex = sex;
		this.dayOfBirth = dayOfBirth;
		this.address = address;
		this.contact = contact;
		this.email = email;
		this.introduction = introduction;
		this.idRights = idRights;
		this.note = note;
		this.idDepartment = idDepartment;
		this.dayOfRest = dayOfRest;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_employee", unique = true, nullable = false)
	public Integer getIdEmployee() {
		return this.idEmployee;
	}

	public void setIdEmployee(Integer idEmployee) {
		this.idEmployee = idEmployee;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sex")
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dayOfBirth", length = 10)
	public Date getDayOfBirth() {
		return this.dayOfBirth;
	}

	public void setDayOfBirth(Date dayOfBirth) {
		this.dayOfBirth = dayOfBirth;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "contact", length = 30)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "introduction", length = 65535)
	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	@Column(name = "id_rights")
	public Integer getIdRights() {
		return this.idRights;
	}

	public void setIdRights(Integer idRights) {
		this.idRights = idRights;
	}

	@Column(name = "note", length = 100)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "id_department")
	public Integer getIdDepartment() {
		return this.idDepartment;
	}

	public void setIdDepartment(Integer idDepartment) {
		this.idDepartment = idDepartment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dayOfRest", length = 10)
	public Date getDayOfRest() {
		return this.dayOfRest;
	}

	public void setDayOfRest(Date dayOfRest) {
		this.dayOfRest = dayOfRest;
	}

}
