package company.entity;
// Generated Dec 14, 2018 12:08:36 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Evaluate generated by hbm2java
 */
@Entity
@Table(name = "evaluate", catalog = "companymanagement")
public class Evaluate implements java.io.Serializable {

	private Integer idEvaluate;
	private Integer idEvaluationEmployee;
	private Integer idEmployeesAreEvaluated;
	private String workDiscipline;
	private String workSpirit;
	private String workloadAchieved;
	private String result;
	private String cumulativeSkill;
	private String orientation;
	private String overallEvaluation;
	private String status;

	public Evaluate() {
	}

	public Evaluate(Integer idEvaluationEmployee, Integer idEmployeesAreEvaluated, String workDiscipline,
			String workSpirit, String workloadAchieved, String result, String cumulativeSkill, String orientation,
			String overallEvaluation, String status) {
		this.idEvaluationEmployee = idEvaluationEmployee;
		this.idEmployeesAreEvaluated = idEmployeesAreEvaluated;
		this.workDiscipline = workDiscipline;
		this.workSpirit = workSpirit;
		this.workloadAchieved = workloadAchieved;
		this.result = result;
		this.cumulativeSkill = cumulativeSkill;
		this.orientation = orientation;
		this.overallEvaluation = overallEvaluation;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_evaluate", unique = true, nullable = false)
	public Integer getIdEvaluate() {
		return this.idEvaluate;
	}

	public void setIdEvaluate(Integer idEvaluate) {
		this.idEvaluate = idEvaluate;
	}

	@Column(name = "id_evaluationEmployee")
	public Integer getIdEvaluationEmployee() {
		return this.idEvaluationEmployee;
	}

	public void setIdEvaluationEmployee(Integer idEvaluationEmployee) {
		this.idEvaluationEmployee = idEvaluationEmployee;
	}

	@Column(name = "id_employeesAreEvaluated")
	public Integer getIdEmployeesAreEvaluated() {
		return this.idEmployeesAreEvaluated;
	}

	public void setIdEmployeesAreEvaluated(Integer idEmployeesAreEvaluated) {
		this.idEmployeesAreEvaluated = idEmployeesAreEvaluated;
	}

	@Column(name = "work_discipline", length = 150)
	public String getWorkDiscipline() {
		return this.workDiscipline;
	}

	public void setWorkDiscipline(String workDiscipline) {
		this.workDiscipline = workDiscipline;
	}

	@Column(name = "work_spirit", length = 150)
	public String getWorkSpirit() {
		return this.workSpirit;
	}

	public void setWorkSpirit(String workSpirit) {
		this.workSpirit = workSpirit;
	}

	@Column(name = "workload_achieved", length = 200)
	public String getWorkloadAchieved() {
		return this.workloadAchieved;
	}

	public void setWorkloadAchieved(String workloadAchieved) {
		this.workloadAchieved = workloadAchieved;
	}

	@Column(name = "result", length = 200)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "cumulative_skill", length = 100)
	public String getCumulativeSkill() {
		return this.cumulativeSkill;
	}

	public void setCumulativeSkill(String cumulativeSkill) {
		this.cumulativeSkill = cumulativeSkill;
	}

	@Column(name = "orientation", length = 45)
	public String getOrientation() {
		return this.orientation;
	}

	public void setOrientation(String orientation) {
		this.orientation = orientation;
	}

	@Column(name = "overall_evaluation", length = 150)
	public String getOverallEvaluation() {
		return this.overallEvaluation;
	}

	public void setOverallEvaluation(String overallEvaluation) {
		this.overallEvaluation = overallEvaluation;
	}

	@Column(name = "status", length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
