package company.entity;
// Generated Dec 14, 2018 12:08:36 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Framework generated by hbm2java
 */
@Entity
@Table(name = "framework", catalog = "companymanagement")
public class Framework implements java.io.Serializable {

	private Integer idFramework;
	private String technology;
	private String describe;

	public Framework() {
	}

	public Framework(String technology, String describe) {
		this.technology = technology;
		this.describe = describe;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_framework", unique = true, nullable = false)
	public Integer getIdFramework() {
		return this.idFramework;
	}

	public void setIdFramework(Integer idFramework) {
		this.idFramework = idFramework;
	}

	@Column(name = "technology", length = 45)
	public String getTechnology() {
		return this.technology;
	}

	public void setTechnology(String technology) {
		this.technology = technology;
	}

	@Column(name = "describe", length = 65535)
	public String getDescribe() {
		return this.describe;
	}

	public void setDescribe(String describe) {
		this.describe = describe;
	}

}
