package company.entity;
// Generated Dec 14, 2018 12:08:36 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FrameworkProject generated by hbm2java
 */
@Entity
@Table(name = "framework_project", catalog = "companymanagement")
public class FrameworkProject implements java.io.Serializable {

	private FrameworkProjectId id;

	public FrameworkProject() {
	}

	public FrameworkProject(FrameworkProjectId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idProject", column = @Column(name = "id_project")),
			@AttributeOverride(name = "idFramework", column = @Column(name = "id_framework", length = 45)),
			@AttributeOverride(name = "note", column = @Column(name = "note", length = 65535)) })
	public FrameworkProjectId getId() {
		return this.id;
	}

	public void setId(FrameworkProjectId id) {
		this.id = id;
	}

}
