package company.entity;
// Generated Dec 14, 2018 12:08:36 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuestManagement generated by hbm2java
 */
@Entity
@Table(name = "quest_management", catalog = "companymanagement")
public class QuestManagement implements java.io.Serializable {

	private Integer idQuest;
	private Integer idProject;
	private String typeOfWork;
	private String nameOfJob;
	private String describ;
	private Date startTime;
	private Date endTime;
	private Integer idEmployee;
	private Date intendTime;
	private String status;

	public QuestManagement() {
	}

	public QuestManagement(Integer idProject, String typeOfWork, String nameOfJob, String describ, Date startTime,
			Date endTime, Integer idEmployee, Date intendTime, String status) {
		this.idProject = idProject;
		this.typeOfWork = typeOfWork;
		this.nameOfJob = nameOfJob;
		this.describ = describ;
		this.startTime = startTime;
		this.endTime = endTime;
		this.idEmployee = idEmployee;
		this.intendTime = intendTime;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_quest", unique = true, nullable = false)
	public Integer getIdQuest() {
		return this.idQuest;
	}

	public void setIdQuest(Integer idQuest) {
		this.idQuest = idQuest;
	}

	@Column(name = "id_project")
	public Integer getIdProject() {
		return this.idProject;
	}

	public void setIdProject(Integer idProject) {
		this.idProject = idProject;
	}

	@Column(name = "typeOfWork", length = 45)
	public String getTypeOfWork() {
		return this.typeOfWork;
	}

	public void setTypeOfWork(String typeOfWork) {
		this.typeOfWork = typeOfWork;
	}

	@Column(name = "nameOfJob", length = 45)
	public String getNameOfJob() {
		return this.nameOfJob;
	}

	public void setNameOfJob(String nameOfJob) {
		this.nameOfJob = nameOfJob;
	}

	@Column(name = "describ", length = 65535)
	public String getDescrib() {
		return this.describ;
	}

	public void setDescrib(String describ) {
		this.describ = describ;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startTime", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endTime", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "id_employee")
	public Integer getIdEmployee() {
		return this.idEmployee;
	}

	public void setIdEmployee(Integer idEmployee) {
		this.idEmployee = idEmployee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "intendTime", length = 19)
	public Date getIntendTime() {
		return this.intendTime;
	}

	public void setIntendTime(Date intendTime) {
		this.intendTime = intendTime;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
