package company.entity;
// Generated Dec 14, 2018 12:08:36 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Skill generated by hbm2java
 */
@Entity
@Table(name = "skill", catalog = "companymanagement")
public class Skill implements java.io.Serializable {

	private Integer idSkill;
	private String nameSkill;
	private String typeOfSkill;
	private String evaluate;
	private String note;
	private Integer idEmployee;

	public Skill() {
	}

	public Skill(String nameSkill, String typeOfSkill, String evaluate, String note, Integer idEmployee) {
		this.nameSkill = nameSkill;
		this.typeOfSkill = typeOfSkill;
		this.evaluate = evaluate;
		this.note = note;
		this.idEmployee = idEmployee;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_skill", unique = true, nullable = false)
	public Integer getIdSkill() {
		return this.idSkill;
	}

	public void setIdSkill(Integer idSkill) {
		this.idSkill = idSkill;
	}

	@Column(name = "name_skill", length = 45)
	public String getNameSkill() {
		return this.nameSkill;
	}

	public void setNameSkill(String nameSkill) {
		this.nameSkill = nameSkill;
	}

	@Column(name = "typeOfSkill", length = 45)
	public String getTypeOfSkill() {
		return this.typeOfSkill;
	}

	public void setTypeOfSkill(String typeOfSkill) {
		this.typeOfSkill = typeOfSkill;
	}

	@Column(name = "evaluate", length = 100)
	public String getEvaluate() {
		return this.evaluate;
	}

	public void setEvaluate(String evaluate) {
		this.evaluate = evaluate;
	}

	@Column(name = "note", length = 150)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "id_employee")
	public Integer getIdEmployee() {
		return this.idEmployee;
	}

	public void setIdEmployee(Integer idEmployee) {
		this.idEmployee = idEmployee;
	}

}
