package entity;
// Generated Dec 14, 2018 12:08:36 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DatabaseProjectId generated by hbm2java
 */
@Embeddable
public class DatabaseProjectId implements java.io.Serializable {

	private Integer idProject;
	private Integer idDatabase;
	private String note;

	public DatabaseProjectId() {
	}

	public DatabaseProjectId(Integer idProject, Integer idDatabase, String note) {
		this.idProject = idProject;
		this.idDatabase = idDatabase;
		this.note = note;
	}

	@Column(name = "id_project")
	public Integer getIdProject() {
		return this.idProject;
	}

	public void setIdProject(Integer idProject) {
		this.idProject = idProject;
	}

	@Column(name = "id_database")
	public Integer getIdDatabase() {
		return this.idDatabase;
	}

	public void setIdDatabase(Integer idDatabase) {
		this.idDatabase = idDatabase;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DatabaseProjectId))
			return false;
		DatabaseProjectId castOther = (DatabaseProjectId) other;

		return ((this.getIdProject() == castOther.getIdProject()) || (this.getIdProject() != null
				&& castOther.getIdProject() != null && this.getIdProject().equals(castOther.getIdProject())))
				&& ((this.getIdDatabase() == castOther.getIdDatabase()) || (this.getIdDatabase() != null
						&& castOther.getIdDatabase() != null && this.getIdDatabase().equals(castOther.getIdDatabase())))
				&& ((this.getNote() == castOther.getNote()) || (this.getNote() != null && castOther.getNote() != null
						&& this.getNote().equals(castOther.getNote())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdProject() == null ? 0 : this.getIdProject().hashCode());
		result = 37 * result + (getIdDatabase() == null ? 0 : this.getIdDatabase().hashCode());
		result = 37 * result + (getNote() == null ? 0 : this.getNote().hashCode());
		return result;
	}

}
