package entity;
// Generated Dec 14, 2018 12:08:36 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DatabaseProject generated by hbm2java
 */
@Entity
@Table(name = "database_project", catalog = "companymanagement")
public class DatabaseProject implements java.io.Serializable {

	private DatabaseProjectId id;

	public DatabaseProject() {
	}

	public DatabaseProject(DatabaseProjectId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idProject", column = @Column(name = "id_project")),
			@AttributeOverride(name = "idDatabase", column = @Column(name = "id_database")),
			@AttributeOverride(name = "note", column = @Column(name = "note", length = 65535)) })
	public DatabaseProjectId getId() {
		return this.id;
	}

	public void setId(DatabaseProjectId id) {
		this.id = id;
	}

}
