package entity;
// Generated Dec 13, 2018 11:00:57 AM by Hibernate Tools 5.3.6.Final

/**
 * Framework generated by hbm2java
 */
public class Framework implements java.io.Serializable {

	private int idFramework;
	private String framework;

	public Framework() {
	}

	public Framework(int idFramework) {
		this.idFramework = idFramework;
	}

	public Framework(int idFramework, String framework) {
		this.idFramework = idFramework;
		this.framework = framework;
	}

	public int getIdFramework() {
		return this.idFramework;
	}

	public void setIdFramework(int idFramework) {
		this.idFramework = idFramework;
	}

	public String getFramework() {
		return this.framework;
	}

	public void setFramework(String framework) {
		this.framework = framework;
	}

}
