package entity;
// Generated Dec 13, 2018 11:00:57 AM by Hibernate Tools 5.3.6.Final

import java.util.Date;

/**
 * ListProject generated by hbm2java
 */
public class ListProject implements java.io.Serializable {

	private int idProject;
	private String idCustomer;
	private String detail;
	private String room;
	private Integer pm;
	private Date starDate;
	private Date endDate;
	private Integer domain;
	private Integer framework;
	private Integer database;
	private Integer programingLanguage;
	private Integer status;

	public ListProject() {
	}

	public ListProject(int idProject) {
		this.idProject = idProject;
	}

	public ListProject(int idProject, String idCustomer, String detail, String room, Integer pm, Date starDate,
			Date endDate, Integer domain, Integer framework, Integer database, Integer programingLanguage,
			Integer status) {
		this.idProject = idProject;
		this.idCustomer = idCustomer;
		this.detail = detail;
		this.room = room;
		this.pm = pm;
		this.starDate = starDate;
		this.endDate = endDate;
		this.domain = domain;
		this.framework = framework;
		this.database = database;
		this.programingLanguage = programingLanguage;
		this.status = status;
	}

	public int getIdProject() {
		return this.idProject;
	}

	public void setIdProject(int idProject) {
		this.idProject = idProject;
	}

	public String getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(String idCustomer) {
		this.idCustomer = idCustomer;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	public Integer getPm() {
		return this.pm;
	}

	public void setPm(Integer pm) {
		this.pm = pm;
	}

	public Date getStarDate() {
		return this.starDate;
	}

	public void setStarDate(Date starDate) {
		this.starDate = starDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getDomain() {
		return this.domain;
	}

	public void setDomain(Integer domain) {
		this.domain = domain;
	}

	public Integer getFramework() {
		return this.framework;
	}

	public void setFramework(Integer framework) {
		this.framework = framework;
	}

	public Integer getDatabase() {
		return this.database;
	}

	public void setDatabase(Integer database) {
		this.database = database;
	}

	public Integer getProgramingLanguage() {
		return this.programingLanguage;
	}

	public void setProgramingLanguage(Integer programingLanguage) {
		this.programingLanguage = programingLanguage;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
