package entity;
// Generated Dec 14, 2018 12:08:36 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MemberProjectId generated by hbm2java
 */
@Embeddable
public class MemberProjectId implements java.io.Serializable {

	private int idEmployee;
	private int idProject;

	public MemberProjectId() {
	}

	public MemberProjectId(int idEmployee, int idProject) {
		this.idEmployee = idEmployee;
		this.idProject = idProject;
	}

	@Column(name = "id_employee", nullable = false)
	public int getIdEmployee() {
		return this.idEmployee;
	}

	public void setIdEmployee(int idEmployee) {
		this.idEmployee = idEmployee;
	}

	@Column(name = "id_project", nullable = false)
	public int getIdProject() {
		return this.idProject;
	}

	public void setIdProject(int idProject) {
		this.idProject = idProject;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MemberProjectId))
			return false;
		MemberProjectId castOther = (MemberProjectId) other;

		return (this.getIdEmployee() == castOther.getIdEmployee()) && (this.getIdProject() == castOther.getIdProject());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEmployee();
		result = 37 * result + this.getIdProject();
		return result;
	}

}
