package entity;
// Generated Dec 13, 2018 11:00:57 AM by Hibernate Tools 5.3.6.Final

/**
 * MemberProject generated by hbm2java
 */
public class MemberProject implements java.io.Serializable {

	private int idProject;
	private String memberName;
	private Integer role;

	public MemberProject() {
	}

	public MemberProject(int idProject) {
		this.idProject = idProject;
	}

	public MemberProject(int idProject, String memberName, Integer role) {
		this.idProject = idProject;
		this.memberName = memberName;
		this.role = role;
	}

	public int getIdProject() {
		return this.idProject;
	}

	public void setIdProject(int idProject) {
		this.idProject = idProject;
	}

	public String getMemberName() {
		return this.memberName;
	}

	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	public Integer getRole() {
		return this.role;
	}

	public void setRole(Integer role) {
		this.role = role;
	}

}
