package entity;
// Generated Dec 14, 2018 12:08:36 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProgramingLanguageProject generated by hbm2java
 */
@Entity
@Table(name = "programing_language_project", catalog = "companymanagement")
public class ProgramingLanguageProject implements java.io.Serializable {

	private Integer idProject;
	private Integer idLanguage;
	private String note;

	public ProgramingLanguageProject() {
	}

	public ProgramingLanguageProject(Integer idLanguage, String note) {
		this.idLanguage = idLanguage;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_project", unique = true, nullable = false)
	public Integer getIdProject() {
		return this.idProject;
	}

	public void setIdProject(Integer idProject) {
		this.idProject = idProject;
	}

	@Column(name = "id_language")
	public Integer getIdLanguage() {
		return this.idLanguage;
	}

	public void setIdLanguage(Integer idLanguage) {
		this.idLanguage = idLanguage;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
