package entity;
// Generated Dec 14, 2018 12:08:36 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "companymanagement")
public class Project implements java.io.Serializable {

	private Integer idProject;
	private String nameProject;
	private Integer idCustomer;
	private String describe;
	private String projectDivision;
	private String projectManager;
	private Date startDate;
	private Date endDate;
	private String domain;
	private String status;

	public Project() {
	}

	public Project(String nameProject, Integer idCustomer, String describe, String projectDivision,
			String projectManager, Date startDate, Date endDate, String domain, String status) {
		this.nameProject = nameProject;
		this.idCustomer = idCustomer;
		this.describe = describe;
		this.projectDivision = projectDivision;
		this.projectManager = projectManager;
		this.startDate = startDate;
		this.endDate = endDate;
		this.domain = domain;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_project", unique = true, nullable = false)
	public Integer getIdProject() {
		return this.idProject;
	}

	public void setIdProject(Integer idProject) {
		this.idProject = idProject;
	}

	@Column(name = "name_project", length = 45)
	public String getNameProject() {
		return this.nameProject;
	}

	public void setNameProject(String nameProject) {
		this.nameProject = nameProject;
	}

	@Column(name = "id_customer")
	public Integer getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(Integer idCustomer) {
		this.idCustomer = idCustomer;
	}

	@Column(name = "describe", length = 65535)
	public String getDescribe() {
		return this.describe;
	}

	public void setDescribe(String describe) {
		this.describe = describe;
	}

	@Column(name = "project_division", length = 45)
	public String getProjectDivision() {
		return this.projectDivision;
	}

	public void setProjectDivision(String projectDivision) {
		this.projectDivision = projectDivision;
	}

	@Column(name = "project_manager", length = 45)
	public String getProjectManager() {
		return this.projectManager;
	}

	public void setProjectManager(String projectManager) {
		this.projectManager = projectManager;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startDate", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "endDate", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "domain", length = 100)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "status", length = 150)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
