package entity;
// Generated Dec 14, 2018 12:08:36 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RelativeInformation generated by hbm2java
 */
@Entity
@Table(name = "relative_information", catalog = "companymanagement")
public class RelativeInformation implements java.io.Serializable {

	private Integer idRelative;
	private String relationship;
	private String name;
	private Date dayOfBirth;
	private String job;
	private String address;
	private Integer idEmployee;

	public RelativeInformation() {
	}

	public RelativeInformation(String relationship, String name, Date dayOfBirth, String job, String address,
			Integer idEmployee) {
		this.relationship = relationship;
		this.name = name;
		this.dayOfBirth = dayOfBirth;
		this.job = job;
		this.address = address;
		this.idEmployee = idEmployee;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_relative", unique = true, nullable = false)
	public Integer getIdRelative() {
		return this.idRelative;
	}

	public void setIdRelative(Integer idRelative) {
		this.idRelative = idRelative;
	}

	@Column(name = "relationship", length = 45)
	public String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dayOfBirth", length = 10)
	public Date getDayOfBirth() {
		return this.dayOfBirth;
	}

	public void setDayOfBirth(Date dayOfBirth) {
		this.dayOfBirth = dayOfBirth;
	}

	@Column(name = "job", length = 45)
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "id_employee")
	public Integer getIdEmployee() {
		return this.idEmployee;
	}

	public void setIdEmployee(Integer idEmployee) {
		this.idEmployee = idEmployee;
	}

}
